<?php

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-10-03 at 22:13:04.
 */
class CustomerTest extends PHPUnit_Framework_TestCase {

    /**
     * @var Customer
     */
    protected $customer;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->customer = new Customer(1, "asd", "asd", "qwe", "asd", 25414);
    }

    
    public function testCustomer() {
        
        $this->assertEquals(1, $this->customer->id);
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

}
